Added GPU related metrics/Codacy errors
VSangarya/AMATSA pull request #33
Opened 2022-10-04 20:08 UTC by atharv67

2022-10-05 15:52 UTC, atharv67 reviewed
Reverting changes of disk and system and pushing

2022-10-07 19:25 UTC, melonpii commented on src/driver.py
> +    tests.test_driver.test_json_validation()
remove this. tests should not be called from driver.py

2022-10-07 19:26 UTC, melonpii commented on src/driver.py
> -    version = config["version"]
why is this removed?

2022-10-07 19:26 UTC, melonpii commented on src/driver.py
> +#from datetime import datetime
this should not be removed

2022-10-07 19:29 UTC, melonpii requested changes
pls check this pr again. It will break things.

2022-10-07 23:52 UTC, atharv67 commented
> pls check this pr again. It will break things.

Working on it

2022-10-07 23:58 UTC, atharv67 commented on src/driver.py
> +#from datetime import datetime
Unused import

2022-10-08 00:14 UTC, atharv67 commented
client_json {
  "metadata": {
    "version": "1.0.0",
    "time": "2022-10-08T00:10:36.080860Z"
  },
  "disk": [
    {
      "name": "/dev/disk1",
      "type": "apfs",
      "total_size": 0.49,
      "used": 0.02,
      "free": 0.47,
      "percentage": 4.08
    },
    {
      "name": "/dev/disk3",
      "type": "apfs",
      "total_size": 228.27,
      "used": 91.21,
      "free": 137.07,
      "percentage": 39.96
    },
    {
      "name": "/dev/disk4",
      "type": "hfs",
      "total_size": 0.02,
      "used": 0.0,
      "free": 0.02,
      "percentage": 0.0
    }
  ],
  "agent": {
    "hostname": "Atharvs-Air.lan",
    "bios_uuid": "00000000-0000-0000-0000-4225bb577fea",
    "platform": "Darwin",
    "release": "21.6.0",
    "version": "Darwin Kernel Version 21.6.0: Sat Jun 18 17:05:47 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8101",
    "machine": "arm64",
    "is64bit": true,
    "physical_cores": 8,
    "logical_cores": 8,
    "total_memory_gb": 8.0
  },
  "metrics": {
    "cpu_load_5min": 19.02,
    "cpu_load_15min": 20.93,
    "avail_memory_gb": 2.03,
    "boot_days_ago": 16
  },
  "network": {
    "mac_address": "42:25:BB:57:7F:EA",
    "ip_address": "192.168.1.221",
    "hostname": "Atharvs-Air.lan",
    "connection_status": true,
    "down_speed": 235.62,
    "up_speed": 12.69,
    "time_now": "20:10:36"
  },
  "gpu": null
}

This is the json finally created

2022-10-08 04:48 UTC, melonpii commented on src/driver.py
> +    print("client_json",client_json)
remove once

2022-10-08 04:48 UTC, melonpii approved these changes

2022-10-08 14:52 UTC, VSangarya approved these changes

2022-10-08 16:32 UTC, merged